### ISSUE TITLE
Core 1 continuously polls RTC to update time

### ISSUE THREAD

**Issue by edward62740** [devKarthikRaj/Project-Nixie-Hardware-Code#1]
Main loop uses a lot of CPU time to continuously poll RTC for time. It would be more efficient to set the PCF2129AT to issue an interrupt every second to read the time, so that the core can do other tasks.

https://github.com/devKarthikRaj/ProjectNixie/blob/68dc4cbe35605d2e41e68a4350058bd806e91936/NixieClockMainCode.ino#L88-L96

**Comment by devKarthikRaj** [comment]
Solved! Now, the ESP32 will poll RTC for time only when the RTC triggers a seconds interrupt.
